definitions:
  model.Rating:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      score:
        type: integer
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This server is part of the Politician application, which allows users
    to view and update ratings for politicians. It uses the Gin framework for handling
    HTTP requests and provides endpoints for retrieving all ratings, retrieving a
    specific rating by ID, and updating a rating based on an action (increment or
    decrement)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Rating Service API
  version: "1.0"
paths:
  /rating/:
    get:
      consumes:
      - application/json
      description: get all ratings, optionally can sort by date (date or -date), and
        score (score or +score)
      parameters:
      - description: Sort by
        in: query
        name: sortBy
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Rating'
      summary: Show all ratings
  /rating/{id}:
    put:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Rating'
      summary: Show an account
      tags:
      - accounts
swagger: "2.0"
